# tasks.py
# Tasks are the specific jobs assigned to each agent.
# 
# Think of it like this:
#   - Agent = The employee (who does the work)
#   - Task  = The assignment given to that employee (what to do)
#
# Each task has:
#   description     = detailed instructions for the agent
#   expected_output = what the finished work should look like
#   agent           = which agent does this task

from crewai import Task


# ═══════════════════════════════════════════════════════════
# TASK 1: Organize the raw research
# (Assigned to: Researcher agent)
# ═══════════════════════════════════════════════════════════
def create_research_task(researcher, topic: str, gemini_result: str, ollama_result: str):
    """
    Gives the Researcher agent the raw outputs from 
    Gemini and Ollama, and asks them to organize it.
    """
    return Task(
        description=f"""
You have been given raw research about "{topic}" from two AI sources.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RAW RESEARCH FROM GEMINI:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{gemini_result}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
RAW RESEARCH FROM OLLAMA (Local AI):
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{ollama_result}

YOUR JOB:
1. Read both research outputs carefully
2. List the TOP 10 most important facts found across both sources
3. Label each fact with which source it came from (Gemini / Ollama / Both)
4. Note 3 areas where both sources AGREE strongly
5. Note any areas where sources DISAGREE or give different information
6. List any important topics that were NOT covered by either source
""",
        expected_output="""A clearly organized document containing:
- Top 10 key facts (labeled by source)
- 3 areas of strong agreement between sources  
- Any disagreements or contradictions found
- Gaps in the research (topics not covered)

Written in clear, professional bullet points.""",
        agent=researcher
    )


# ═══════════════════════════════════════════════════════════
# TASK 2: Analyze and find insights
# (Assigned to: Analyst agent)
# ═══════════════════════════════════════════════════════════
def create_analysis_task(analyst, topic: str):
    """
    Gives the Analyst agent the organized research 
    and asks them to find deep insights and patterns.
    """
    return Task(
        description=f"""
Based on the organized research about "{topic}", perform a deep strategic analysis.

YOUR JOB:
1. Identify the TOP 5 most important insights 
   (rate each as: 🔴 Critical / 🟡 Important / 🟢 Interesting)
   
2. Find PATTERNS — what themes keep appearing across the research?

3. Identify PRACTICAL APPLICATIONS — how can businesses or 
   individuals USE this information right now?
   
4. Spot OPPORTUNITIES — what gaps or future possibilities exist?

5. List KEY RISKS or challenges someone should be aware of

6. Write a "So What?" paragraph — explain in simple terms 
   WHY this topic matters to the average person
""",
        expected_output="""A strategic analysis document containing:
- Top 5 insights (with importance ratings)
- Key patterns identified
- Practical applications (at least 3)
- Opportunities spotted
- Key risks to be aware of
- "So What?" paragraph in simple language

Written clearly so a non-expert can understand it.""",
        agent=analyst
    )


# ═══════════════════════════════════════════════════════════
# TASK 3: Write the final report
# (Assigned to: Writer agent)
# ═══════════════════════════════════════════════════════════
def create_writing_task(writer, topic: str):
    """
    Gives the Writer agent all previous work and asks 
    them to produce the final polished report.
    """
    return Task(
        description=f"""
Using ALL the research and analysis done so far about "{topic}", 
write a final professional report that is ready for presentation.

YOUR JOB:
Write a complete, polished report that:
- Is easy to read (avoid unnecessary jargon)
- Is well structured with clear headings
- Can be understood by someone who knows nothing about the topic
- Would impress a senior manager or executive
- Can be directly uploaded to NotebookLM or turned into slides

IMPORTANT FORMATTING RULES:
- Use markdown formatting (## for headings, **bold** for key terms)
- Keep each section focused and concise
- Use bullet points where appropriate
- Include a word count estimate at the end
""",
        expected_output="""A complete professional research report in Markdown format with:

# [Report Title]

## Executive Summary (3-4 sentences)
## Background & Overview
## Key Findings (most important discoveries)
## Applications & Use Cases (real world examples)
## Challenges & Limitations
## Future Outlook & Opportunities  
## Recommendations (what to do with this information)
## Conclusion

---
*Sources: Google Gemini 1.5 Flash + Ollama Llama3.2*
*Generated by AI Research Agent System*

The report should be comprehensive, professional, and presentation-ready.""",
        agent=writer
    )